


version: '3.7'

# Define services
services:
  # App backend service
  app_server:
  #   # Configuration for building the docker image for the backend service
    container_name: app_server
    build:
      args :
        JAR_FILE: /build/libs/insurance-0.0.1-SNAPSHOT.jar
      context: ./insurance 
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/InsuranceDB?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: pass
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - nginx


  # # Frontend Service
  nginx:
    build: ./insurance-mmc
    restart: always
    ports:
      - 4200:80
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro


  # Database Service (Postgresql)
  db:
    image: postgres:latest
    container_name: db
    ports:
    - "5432:5432"
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DATABASE: 'InsuranceDB'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_ROOT_PASSWORD: 'adminadmin'
      #MYSQL_ROOT_HOST: 'localhost' #Host '172.24.0.3' is not allowed to connect to this MySQL server
    networks:
      - backend


# Networks to be created to facilitate communication between containers
networks:
  backend:
  nginx:
