version: '3.7'

# Define services
services:
  # App backend service
  app_server:
  #   # Configuration for building the docker image for the backend service

    build:
      args :
        JAR_FILE: /build/libs/*.jar
      context: ./insurance 
      dockerfile:
        Dockerfile
    ports:
      - "8085:5432" 
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/InsuranceDB?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - nginx


  # # Frontend Service
  nginx:
    build: ./insurance-mmc/insurance-mmc
    restart: always
    ports:
      - 5001:80
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro


  # Database Service (Mysql)
  db:
    image: mysql:latest
    ports:
      - "6033:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'InsuranceDB'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    networks:
      - backend


# Networks to be created to facilitate communication between containers
networks:
  backend:
  nginx: