version: '3.7'

# Define services
services:
  # App backend service
  server:
    # Configuration for building the docker image for the backend service

    build:
      args :
        JAR_FILE: /build/libs/*.jar
      context: ./insurance # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile:
        Dockerfile
    ports:
      - "8085:8085" 
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/InsuranceDB?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service
  client:
    build:
      context: ./insurance-mmc/insurance-mmc # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - server
    networks:
      - frontend

  # Database Service (Mysql)
  db:
    image: mysql:latest
    ports:
      - "6033:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'InsuranceDB'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    networks:
      - backend


# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: