


version: '3.7'

# Define services
services:
  # App backend service
  app_server:
  #   # Configuration for building the docker image for the backend service
    container_name: app_server
    build:
      args :
        JAR_FILE: /build/libs/insurance-0.0.1-SNAPSHOT.jar
      context: ./insurance 
      dockerfile:
        Dockerfile
    ports:
      - "8081:8085" 
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/InsuranceDB?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - nginx


  # # Frontend Service
  nginx:
    build: ./insurance-mmc
    restart: always
    ports:
      - 4200:80
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro


  # Database Service (Mysql)
  db:
    image: mysql:latest
    ports:
      - "3306:6033"
    restart: always
    environment:
      MYSQL_DATABASE: 'InsuranceDB'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%' #Host '172.24.0.3' is not allowed to connect to this MySQL server
    networks:
      - backend


# Networks to be created to facilitate communication between containers
networks:
  backend:
  nginx: